#cloud-config
merge_how: dict(recurse_array)+list(append)
write_files:
  - path: /var/remora/default-env.sh
    owner: "root:root"
    permissions: "0600"
    content: |
      NODE_IP="$NODE_IP"
      ETCD_ENDPOINT="$ETCD_ENDPOINT"
      DOCKER_PATH="$DOCKER_PATH"
      KUBERNETES_SERVICE_IP="$KUBERNETES_SERVICE_IP"
      KUBE_PORT="$KUBE_PORT"
      KUBE_VERSION="$KUBE_VERSION"
      KUBE_ADMISSION_CONTROL="$KUBE_ADMISSION_CONTROL"
      KUBE_SERVICE_IP_RANGE="$KUBE_SERVICE_IP_RANGE"
      KUBE_DNS_SERVER_IP="$KUBE_DNS_SERVER_IP"
      KUBE_CLUSTER_CIDR="$KUBE_CLUSTER_CIDR"
      HYPERKUBE_IMAGE_REPO="$HYPERKUBE_IMAGE_REPO"
      FLANNEL_IMAGE_REPO="$FLANNEL_IMAGE_REPO"
      FLANNEL_VER="${FLANNEL_VER}"
      FLANNEL_BACKEND_TYPE="$FLANNEL_BACKEND_TYPE"
      CLOUD_PROVIDER="$CLOUD_PROVIDER"
