heat_template_version: 2014-10-16

parameters:


  pool_id:
    type: string
    default: ""
    description: "Pesudo pool id."

  port_id:
    type: string
    default: ""

  address:
    type: string
    default: ""

  protocol_port:
    type: number
    default: 443

  subnet_id:
    type: string
    default: ""

resources:
  floating_association:
    type: OS::Neutron::FloatingIPAssociation
    property:
      floatingip_id: { get_param: pool_id }
      port_id: { get_param: port_id }
