heat_template_version: 2014-10-16

description: >
  This is a stack that defines a single Kubernetes master node.

parameters:

  # Infra

  etcd_servers:
    type: string
    description: List of etcd servers to connect with (scheme://ip:port), comma separated.

  # Server

  image:
    type: string
    description: glance image used to boot the server.

  flavor:
    type: string
    description: flavor to use when booting the server.

  key_name:
    type: string
    description: name of ssh key to be provisioned on our server.

  subnet:
    type: string
    description: Subnet from which to allocate fixed addresses.

  security_group:
    type: string
    description: ID of the security group for kubernetes master.

  # Kubernetes

  kube_port:
    type: number
    description: >
      The port which are used by kube-apiserver to provide Kubernetes
      service.

  kube_allow_privileged:
    type: string
    description: >
      whether or not kubernetes should permit privileged containers.
    constraints:
      - allowed_values: ["true", "false"]

  kube_admission_control:
    type: string
    description: >
      List of admission control plugins to activate

  kube_version:
    type: string
    description: version of kubernetes used for kubernetes cluster

  # Docker

  # OpenStack

resources:

outputs:
