---
node_groups:
  master:
    spec:
      kubernetes:
        labels:
          - "node-role.kubernetes.io/master"
        taints:
          - "node-role.kubernetes.io/master=:NoSchedule"
    nodes:
    - "192.168.1.111"
    - "192.168.1.112"
  master_arm64:
    spec:
      kubernetes:
        labels:
          - "node-role.kubernetes.io/master"
        taints:
          - "node-role.kubernetes.io/master=:NoSchedule"
        image:
          repository: "gcr.io/google_containers/hyperkube-arm64"
    nodes:
    - "192.168.1.113"
  worker:
    nodes:
    - "192.168.1.121"
  worker_arm64:
    spec:
      kubernetes:
        image:
          repository: "gcr.io/google_containers/hyperkube-arm64"
        labels:
          - "node-role.kubernetes.io/master-arm64"
          - "node-role.kubernetes.io/master"
          - sub-label1: 
            - subsub-label1: 
              - "subsub1-1-arm64"
          - sub-label1:
            - "hogehoge"
    nodes:
    - "192.168.1.131"
  worker_arm:
    spec:
      kubernetes:
        image:
          repository: "gcr.io/google_containers/hyperkube-arm"
    nodes:
    - "192.168.1.141"

spec:
  kubernetes:
    image:
      repository: "gcr.io/google_containers/hyperkube-default"
      tag: "v1.8.2"
      pullPolicy: "Always"
    labels:
      - "node-role.kubernetes.io/master-default"
      - "node-role.kubernetes.io/master"
      - sub-label1: 
        - "sub1-1-default"
        - "sub1-2-default"
        - subsub-label1:
          - "subsub1-1-default"
          - "subsub1-2-default"
      - sub-label2: 
        - "sub2-1-default"
        - subsub-label12:
          - "subsub2-1-default"
    some-key1:
      - "some-key1-1-default"
    some-key2: "some-key2-default"
