---
# Username of target VMs
# If you use Ubuntu, change below line to like `user: ubuntu`.
user: core

local:
  assets_dir: "~/.kube/assets"

masters: &masters
  - 192.168.1.111
  - 192.168.1.112
  - 192.168.1.113
workers: &workers
  - 192.168.1.121
  - 192.168.1.122
  - 192.168.1.123

hosts:
  192.168.1.111: 
    arch: arm
  192.168.1.112: 
    arch: arm
  192.168.1.113: 
    arch: arm
  192.168.1.121: 
    arch: arm64
  192.168.1.122: 
    arch: arm64
  192.168.1.123: 
    arch: arm64

roledefs:
  bootstrap:
  - 192.168.1.111
  etcd: *masters
  master: *masters
  worker: *workers

kubernetes:
  # Public kubernetes service address
  public_service_ip: 192.168.1.101
