---
user: core

masters: &masters
  - 192.168.1.111
  - 192.168.1.112
  - 192.168.1.113
workers: &workers
  - 192.168.1.121
  - 192.168.1.122
  - 192.168.1.123
  - 192.168.1.124
  - 192.168.1.125
  - 192.168.1.126

roledefs:
  haproxy: *masters
  etcd: *masters
  apiserver: *masters
  controller_manager: *masters
  scheduler: *masters
  worker: *workers

haproxy:
  keepalived_net_range: 16
  keepalived_net_device: eth0

kubernetes:
  public_service_ip: 192.168.1.101

flannel:
  backend_type: host-gw
