---
# Username of target VMs
# If you use Ubuntu, change below line to like `user: ubuntu`.
user: core

local:
  assets_dir: "~/.kube/assets"

masters: &masters
  - 192.168.1.111
  - 192.168.1.112
  - 192.168.1.113
workers: &workers
  - 192.168.1.121
  - 192.168.1.122
  - 192.168.1.123

roledefs:
  bootstrap:
  - 192.168.1.111
  etcd: *masters
  master: *masters
  worker: *workers

haproxy:
  # network range which keepalived use
  keepalived_net_range: 16
  # network interface which keepalived use
  keepalived_net_device: eth0

kubernetes:
  # Public kubernetes service address
  public_service_ip: 192.168.1.101
