#!/usr/bin/env bash
set -eu
export LC_ALL=C

cat <<EOF
#cloud-config
# Before commit any change please validate this file @ https://coreos.com/validate/

# Set hostname
hostname: ${_NODE_HOSTNAME}

# Set SSH Key
ssh_authorized_keys:
- ${NODE_PUBLIC_KEY}

coreos:
  update:
    reboot-strategy: ${COREOS_REBOOT_STRATEGY:-"etcd-lock"}
  etcd2:
    proxy: on
    discovery: ${DISCOVERY_URL}
    listen-client-urls: http://127.0.0.1:2379
    cert-file: /etc/kubernetes/ssl/worker.pem
    key-file: /etc/kubernetes/ssl/worker-key.pem
    trusted-ca-file: /etc/kubernetes/ssl/ca.pem
    peer-cert-file: /etc/kubernetes/ssl/worker.pem
    peer-key-file: /etc/kubernetes/ssl/worker-key.pem
    peer-trusted-ca-file: /etc/kubernetes/ssl/ca.pem
  units:
    - name: etcd2.service
      command: start
    - name: 00-${NODE_NET_DEVICE}.network
      runtime: true
      content: |
        [Match]
        Name=${NODE_NET_DEVICE}

        [Network]
        DNS=${NODE_DNS}
        Address=${_NODE_ADDRESS}/${NODE_NETWORK_RANGE}
        Gateway=${NODE_GATEWAY}
EOF
