#cloud-config
# Before commit any change please validate this file @ https://coreos.com/validate/

# Set hostname
hostname: _HOSTNAME_

# Set SSH Key
ssh_authorized_keys:
- _PUBLIC_KEY_

coreos:
  etcd2:
    proxy: on
    discovery: _DISCOVERY_URL_
    listen-client-urls: http://127.0.0.1:2379
    cert-file: /etc/kubernetes/ssl/worker.pem
    key-file: /etc/kubernetes/ssl/worker-key.pem
    trusted-ca-file: /etc/kubernetes/ssl/ca.pem
    peer-cert-file: /etc/kubernetes/ssl/worker.pem
    peer-key-file: /etc/kubernetes/ssl/worker-key.pem
    peer-trusted-ca-file: /etc/kubernetes/ssl/ca.pem
  units:
    - name: etcd2.service
      command: start
    - name: 00-_NET_DEVICE_.network
      runtime: true
      content: |
        [Match]
        Name=_NET_DEVICE_

        [Network]
        DNS=_DNS_
        Address=_ADDRESS_/_NETWORK_RANGE_
        Gateway=_GATEWAY_
